add ocaml-general
kxcteam/pubinfra.dockerfiles pull request #3
Opened 2022-07-27 06:44 UTC by kxc-hongoh

## Summary

- add `ocaml-general/Dockerfile`

## GitHub Container Registry
[https://github.com/orgs/kxcteam/packages/container/package/ocaml-general](https://github.com/orgs/kxcteam/packages/container/package/ocaml-general)

2022-07-27 13:57 UTC, haochenx requested changes

2022-07-27 13:57 UTC, haochenx commented on ocaml-general/Dockerfile
> +RUN opam init --auto-setup --yes --disable-sandboxing
follow https://stackoverflow.com/c/kxcteam/a/22/1 to init opam

2022-07-28 06:21 UTC, kxc-hongoh commented
```bash
docker build -t ghcr.io/kxcteam/ocaml-general:4.13.1 --build-arg VER=4.13.1 ocaml-general
```
のように`--build-arg VER=X.XX.X`を与えることでbuildするOCamlのバージョンを指定できます。
省略した場合のデフォルト値は`4.12.1`です。

2022-07-28 12:57 UTC, haochenx requested changes
https://github.com/kxcteam/pubinfra.dockerfiles/issues/4
全部いれてほしい
(slack でも書きました
https://kxcteam.slack.com/archives/C03QDBJEUEA/p1658930896276209)

2022-07-29 12:17 UTC, haochenx commented
@kxc-waddlaw さんもレビューしてほしい

2022-07-29 12:49 UTC, haochenx requested changes

2022-07-29 12:49 UTC, haochenx commented on ocaml-general/Dockerfile
> +  yarn \
あ、こういうふうに install した yarn が多分われわれが使いたい yarn とは別のものになると思います。

`npm install -g yarn` でinstallしましょう

2022-08-01 06:25 UTC, kxc-waddlaw commented on ocaml-general/Dockerfile
> +  merlin \
`merlin` はバージョン指定無しで良いですか？

2022-08-01 06:25 UTC, kxc-waddlaw commented on ocaml-general/Dockerfile
> +  && rm -rf /var/lib/apt/lists/*
`rm -rf /var/lib/apt/lists/*` は `ubuntu` image であれば不要っぽい

- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-ge

2022-08-01 06:27 UTC, kxc-waddlaw commented
@haochenx このイメージの利用用途と目的は以下の通りで良いでしょうか？

- 主に github actions で利用するベースイメージ
- 既存の ocaml-setup だと速度が遅いので、それを改善したい

2022-08-03 09:08 UTC, kxc-waddlaw approved these changes

2022-08-04 08:00 UTC, haochenx commented on ocaml-general/Dockerfile
> +  merlin \
merlin はひとまずよいのです。

2022-08-04 08:01 UTC, haochenx approved these changes
LGTM

2022-08-04 08:01 UTC, merged